// src/components/async-button.vue
<script lang="ts" setup>
const props = defineProps({
  onClick: {
    type: Function,
    default: null,
  },
})

let done = $ref(false)

async function handleClick () {
  const ret = props.onClick?.()
  if (ret instanceof Promise) {
    await ret
    done = true
    setTimeout(() => done = false, 2000)
  }
}
</script>

<template lang="pug">
button(class="relative" @click="handleClick")
  slot(:done="done")
  transition(
    v-if="$slots.async"
    enter-from-class="opacity-0 scale-0"
    leave-to-class="opacity-0"
    enter-active-class="transition duration-200 ease-in-out"
    leave-active-class="transition duration-200 ease-in-out"
  )
    div(v-show="done" class="absolute inset-0")
      slot(name="async")
</template>

// src/components/async-button.tsx
import { type ButtonHTMLAttributes, type ReactNode, useState } from 'react'

interface AsyncButtonProps extends Omit<
  ButtonHTMLAttributes<HTMLButtonElement>,
  'children' | 'onClick'
> {
  children: (done: boolean) => ReactNode
  doneIcon?: ReactNode
  onClick?: () => Promise<void> | void
}

export function AsyncButton({
  children,
  className = '',
  doneIcon,
  onClick,
  ...props
}: AsyncButtonProps) {
  const [done, setDone] = useState(false)

  async function handleClick() {
    await onClick?.()
    setDone(true)
    window.setTimeout(() => setDone(false), 2000)
  }

  return (
    <button className={`relative ${className}`} type="button" onClick={handleClick} {...props}>
      <span className={done ? 'opacity-0' : 'opacity-100'}>{children(done)}</span>
      {doneIcon ? (
        <span
          aria-hidden="true"
          className={`absolute inset-0 grid place-items-center ${done ? 'scale-100 opacity-100' : 'scale-0 opacity-0'} transition duration-200 ease-in-out`}
        >
          {doneIcon}
        </span>
      ) : null}
    </button>
  )
}
